### ISSUE TITLE
Add 'variables' section in the modules yaml file

### ISSUE THREAD

**Issue by mas2020** [mas2020-golang/goal#95]
Add a section dedicated to the variables that can be referenced later on the in the module with the syntax `$VARIABLE`, for example:
```yaml
name: remote
author: "@mas2020"
description: |
  File commands package is a package to work with files and directories of a remote HOST.
version: 0.6.0
variables:
  ACTIVITY: "\e[1;34m➜\e[1;97m"
```
As you can see we have the variables section where we define a variable called ACTIVITY that we can reference in the cmd property as $ACTIVITY.
